# Generated by Django 4.1.7 on 2023-03-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecommerce_app', '0003_alter_product_categories_cartitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='title',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='is_cart_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
